/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoteNoteIdRouteImport } from './routes/note.$noteId'
import { Route as BoardBoardIdRouteImport } from './routes/board.$boardId'
import { Route as ApiVisionRouteImport } from './routes/api/vision'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteNoteIdRoute = NoteNoteIdRouteImport.update({
  id: '/note/$noteId',
  path: '/note/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardBoardIdRoute = BoardBoardIdRouteImport.update({
  id: '/board/$boardId',
  path: '/board/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVisionRoute = ApiVisionRouteImport.update({
  id: '/api/vision',
  path: '/api/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learn': typeof LearnRoute
  '/library': typeof LibraryRoute
  '/notes': typeof NotesRoute
  '/api/chat': typeof ApiChatRoute
  '/api/vision': typeof ApiVisionRoute
  '/board/$boardId': typeof BoardBoardIdRoute
  '/note/$noteId': typeof NoteNoteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/learn': typeof LearnRoute
  '/library': typeof LibraryRoute
  '/notes': typeof NotesRoute
  '/api/chat': typeof ApiChatRoute
  '/api/vision': typeof ApiVisionRoute
  '/board/$boardId': typeof BoardBoardIdRoute
  '/note/$noteId': typeof NoteNoteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/learn': typeof LearnRoute
  '/library': typeof LibraryRoute
  '/notes': typeof NotesRoute
  '/api/chat': typeof ApiChatRoute
  '/api/vision': typeof ApiVisionRoute
  '/board/$boardId': typeof BoardBoardIdRoute
  '/note/$noteId': typeof NoteNoteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/learn'
    | '/library'
    | '/notes'
    | '/api/chat'
    | '/api/vision'
    | '/board/$boardId'
    | '/note/$noteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/learn'
    | '/library'
    | '/notes'
    | '/api/chat'
    | '/api/vision'
    | '/board/$boardId'
    | '/note/$noteId'
  id:
    | '__root__'
    | '/'
    | '/learn'
    | '/library'
    | '/notes'
    | '/api/chat'
    | '/api/vision'
    | '/board/$boardId'
    | '/note/$noteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LearnRoute: typeof LearnRoute
  LibraryRoute: typeof LibraryRoute
  NotesRoute: typeof NotesRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiVisionRoute: typeof ApiVisionRoute
  BoardBoardIdRoute: typeof BoardBoardIdRoute
  NoteNoteIdRoute: typeof NoteNoteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note/$noteId': {
      id: '/note/$noteId'
      path: '/note/$noteId'
      fullPath: '/note/$noteId'
      preLoaderRoute: typeof NoteNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$boardId': {
      id: '/board/$boardId'
      path: '/board/$boardId'
      fullPath: '/board/$boardId'
      preLoaderRoute: typeof BoardBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vision': {
      id: '/api/vision'
      path: '/api/vision'
      fullPath: '/api/vision'
      preLoaderRoute: typeof ApiVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LearnRoute: LearnRoute,
  LibraryRoute: LibraryRoute,
  NotesRoute: NotesRoute,
  ApiChatRoute: ApiChatRoute,
  ApiVisionRoute: ApiVisionRoute,
  BoardBoardIdRoute: BoardBoardIdRoute,
  NoteNoteIdRoute: NoteNoteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
